const ActionTypes = {
  SHOW_ORDER: "SHOW_ORDER",
  HIDDEN_ORDER: "HIDDEN_ORDER",
  GET_USER: "GET_USER",
  SHOW_MODAL: "SHOW_MODAL",
  HIDDEN_MODAL: "HIDDEN_MODAL",
  SHOW_DELETE: "SHOW_DELETE",
  HIDDEN_DELETE: "HIDDEN_DELETE",
  OKEY_DELETE: "OKEY_DELETE",
  RESET_ISDLETE: "RESET_ISDLETE",
  LOAD_DATA_DESCRIPTION: "LOAD_DATA_DESCRIPTION",
  LOAD_DATA_ORDER: "LOAD_DATA_ORDER",
  SAVE: "SAVE",
  OKEY_DELETE_PRODUCT: "OKEY_DELETE_PRODUCT",
};
export default ActionTypes;
